* renotebook :TOC:
  - [[#introduction][Introduction]]
  - [[#installation][Installation]]
  - [[#usage][Usage]]
  - [[#options][Options]]
  - [[#useful-tools-used-by-this-project][Useful Tools used by this Project]]
  - [[#useful-clojure-libraries][Useful Clojure Libraries]]
  - [[#license][License]]

** Introduction
Tool for programatically working with reMarkable Notebooks

** Installation
Download from https://github.com:PaulSchulz/renotebook.git

** Usage
FIXME: explanation

    $ java -jar renotebook-0.1.0-standalone.jar [args]

** Options

FIXME: listing of options this app accepts.

** Useful Tools used by this Project
*** reMArkable Entware
Follow the instructions from Github
- [[https://github.com/Evidlo/remarkable_entware]]

Installation may require linking the /opt directory.
#+begin_src shell
  ln -s /home/root/.entware /opt
#+end_src

Once installed, additional software can be installed from the Entware and Toltec
repositories using 'opkg'.

*** Rsync (opkg install rsync)

Rsync is usefull for backing up and copying the Remarkable documents.
#+begin_src shell
  cd ~/Documents
  rsync -info=STATS --human-readable \
    -r root@$HOST:/home/root/.local/share/remarkable/xchitl/ remarkable/
#+end_src

** Useful Clojure Libraries
The following are some Clojure Libraries that have proved to be useful. They may currently be used, or noted here for future reference.

- clj-ssh.cli and clj-ssh.ssh for executing remote ssh commands on remarkable tablet.

** License

Copyright © 2021 Paul Schulz

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
